version: "3"
services:
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/app/
        restart: always
        command: gunicorn -w 2 -b 0.0.0.0:5000 --reload app:app
        logging:
            driver: "json-file"
            options:
                max-size: "10M"
                max-file: "2"

    db:
        build:
            context: .
            dockerfile: DB_Dockerfile
        ports:
            - "3306:3306"
        volumes:
            - ./db:/app/
        restart: always
        expose:
            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
        logging:
            driver: "json-file"
            options:
                max-size: "10M"
                max-file: "2"

